version: "3"

services:


  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0

    ports:
      - "9200:9200"
      - "9300:9300"


    networks:
      - esnet

  kibana1:
    image: docker.elastic.co/kibana/kibana:6.4.0

    ports:
      - 5601:5601

    depends_on:
      - elasticsearch

    networks:
      - esnet

networks:
  esnet:

